# Generated by Django 3.0.5 on 2020-06-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200614_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='discription',
            new_name='description',
        ),
    ]
